### ISSUE TITLE
Question: Wouldn't simplified standards suffice?

### ISSUE THREAD

**Issue by Potherca** [pixelandtonic/CodingStandards#2]
As these coding standards look a lot like PSR2, wouldn't it be better (from both a readability and a maintenance point of view) to only stipulate the points in which these standards differ from PSR2?

That would make it a lot easier to understand which parts are Craft specific and which are generic.

This would also be helpful if one were, for instance, planning on creating a Code Sniff for craft :smile_cat:

**Comment by tonynelson19** [comment]
Or better yet, just use PSR2 and leverage existing tools already supported by the larger PHP community, like https://github.com/FriendsOfPHP/PHP-CS-Fixer

**Comment by angrybrad** [comment]
The upcoming Craft 3 (based on Yii 2) is PSR2.
